import verifiedFactsData from "@/data/verified-facts.json";
import type { CenterFact } from "@/types/center";

interface ReviewedCenterEntry {
  checkedAt: string;
  indexableFrom?: string;
  summary?: boolean;
  facts: Omit<CenterFact, "checkedAt">[];
}

export interface ReviewedCenter {
  facts: CenterFact[];
  /** ISO date (YYYY-MM-DD) from which the ficha may be indexed. */
  indexableFrom?: string;
  /** True when the short description was written by hand from the facts. */
  hasEditorialSummary: boolean;
}

// Generated by scripts/build-verified-facts.mjs. Keyed by center slug.
const REVIEWED = verifiedFactsData as unknown as Record<string, ReviewedCenterEntry>;

/**
 * Review result for a center, or `undefined` when it has not been reviewed yet.
 * A reviewed center can legitimately have no facts (dead website, nothing
 * published): the entry still matters, because it switches the ficha from the
 * legacy indexability rule to the verified-facts one.
 */
export function getReviewedCenter(slug: string): ReviewedCenter | undefined {
  const entry = REVIEWED[slug];
  if (!entry) return undefined;
  return {
    indexableFrom: entry.indexableFrom,
    hasEditorialSummary: entry.summary === true,
    facts: entry.facts.map((fact) => ({ ...fact, checkedAt: entry.checkedAt })),
  };
}
